repository:
    name: openid-client-server-redis-session
    description: A Redis session store for @optum/openid-client-server.
    topics: redis, sessionstorage, openid, openid-client-server
    private: false

    has_issues: true
    has_projects: false
    has_wiki: false
    has_downloads: true

    default_branch: master

    allow_squash_merge: true
    allow_merge_commit: false
    allow_rebase_merge: false

branches:
    - name: master
      protection:
          required_pull_request_reviews:
              required_approving_review_count: 1
              dismiss_stale_reviews: true
          required_status_checks:
              strict: true
              contexts: [test]
